### ISSUE TITLE
BUG: Annotation UI comment field not taking text input

### ISSUE THREAD

**Issue by scottveirs** [coastal-science/HALLO-annotation#22]
As an authenticated annotator, 
when I create a new annotation or edit an existing one,
I can select the Comment field for an annotation (and see my cursor ready there), 
but when I try to type text nothing happens.

I've tested this on OSX (12.6) / Macbook (16-inch, 2019) and get same behavior on both Chrome (v.107.0.5304.110) and Safari(Version 16.0 (17614.1.25.9.10, 17614)).

**Comment by scottveirs** [comment]
@yue-su and @fsfrazao 

I'd label this as a bug and a high-priority one as -- ideally -- I'd be leaving comments as I beta-test annotation of all signals in the JKL 30-minute test set.

**Comment by yue-su** [comment]
the issue has been resolved with the latest update.
